CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password_hash" varchar NOT NULL,
  "full_name" varchar,
  "role" varchar NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "last_login" timestamp
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" text,
  "sku" varchar,
  "barcode" varchar UNIQUE NOT NULL,
  "status" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "created_by" int NOT NULL,
  "updated_by" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "parent_id" int,
  "icon" varchar,
  "sort_order" int
);

CREATE TABLE "product_categories" (
  "product_id" int,
  "category_id" int,
  PRIMARY KEY ("product_id", "category_id")
);

CREATE TABLE "inventory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL DEFAULT 0,
  "min_stock" int DEFAULT 0,
  "max_stock" int,
  "location" varchar,
  "last_updated" timestamp DEFAULT (now())
);

CREATE TABLE "pricing" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "cost_price" decimal(10,2),
  "selling_price" decimal(10,2) NOT NULL,
  "markup_percentage" decimal(5,2),
  "currency" varchar DEFAULT 'ARS',
  "valid_from" timestamp DEFAULT (now()),
  "valid_to" timestamp,
  "created_by" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "audit_log" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_name" varchar NOT NULL,
  "record_id" int NOT NULL,
  "action" varchar NOT NULL,
  "old_values" json,
  "new_values" json,
  "user_id" int,
  "ip_address" varchar,
  "user_agent" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "product_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "image_url" varchar NOT NULL,
  "is_primary" boolean DEFAULT false,
  "sort_order" int DEFAULT 0
);

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("id");

ALTER TABLE "product_categories" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "product_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "pricing" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "pricing" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "audit_log" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");
